configured_endpoints: 235
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-fb374aa97ce3c90e9b59c6529283b63dbdcebcf8a524aeac9c2612895efdee3b.yml
openapi_spec_hash: 4aa9ad6b7c300dbe420ed35805829af8
config_hash: 1ca21e38ca9524a8bb562eabd5ec8db1
