configured_endpoints: 251
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-321ffeb106c6033b1265b0da8fa396bcdefcb5fc8eb35df81cfaadd21486832c.yml
openapi_spec_hash: a32cc0ebaa8200fe2b70eb58a57d6a6e
config_hash: 53aff2d4fd59691d99b1a4d5fc2ca1fa
