configured_endpoints: 212
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-7ccd9175feeddf9d90de4e4871d58e66fbc61b697cdbd30cce41f5f6ef8da15b.yml
openapi_spec_hash: 0fa2b527c2b223e916f0612df8996be5
config_hash: e0cffca8de3b5c618b06a5ef34cfc9f4
