configured_endpoints: 106
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-28a8ac0edb9f62ab28cdedee02110b6452af818460c9eaedfc93b211ac93fbeb.yml
openapi_spec_hash: 95acdaaa033998de17e3b1baf4a1887c
config_hash: bb33eca396584c96af9cafbfd209b1f3
