configured_endpoints: 236
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-7f2b37c806dbc4dde966becd0033f877fc1acf3cc52bd6b58e95bd977dcc2a40.yml
openapi_spec_hash: 06c5eb74fa1f8f676ca69364ecf28a5e
config_hash: b82df89d6a8b4fd3739d4b2eb3f6a77e
