configured_endpoints: 225
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/structify%2Fstructify-e1a9a56aa2dbc4deb6a3d6eed2868c0ed85bf9f939ab77fa42e3fed2cbbdac28.yml
openapi_spec_hash: 3e27f5674dc57c757e03a97068e9a240
config_hash: 1ce43d9a4ca1ccdba0c1af0abe439a7b
